### ISSUE TITLE
Close bubbly

### ISSUE THREAD

**Issue by fdaciuk** [siduck/bubbly#3]
Hi @siduck! This is a great project, thanks! ❤️ 

I'm trying bubbly in Manjaro Gnome, and it works perfectly!

The only issue is I can't stop it! Is there a way to easily do this, instead of just `kill -9 <bubbly_process>`?

**Comment by siduck** [comment]
hi @fdaciuk 

press Ctrl + Escape key

**Comment by siduck** [comment]
or just this 

killall eww getkeys.sh

![image](https://github.com/siduck/bubbly/assets/59060246/6c40a0c2-d65e-4c0f-949c-6f0e1df49d22)

**Comment by fdaciuk** [comment]
Great, thanks!
